version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "5007:3306"
    networks:
      - app-network

  backend:
    build:
      context: ./api
    container_name: backend
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PORT: 5000
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5008:5000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./
    container_name: frontend
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5009:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
